server:
  port: 8080
#数据库配置
spring:
  application:
    name:blackjack
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bigevent?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: JJ123456

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: edu.czjtu.blackjack.entity
  configuration:
    map-underscore-to-camel-case: true # 驼峰命名规则
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

